version: '3.8'
services:
  aincome-app:
    container_name: aincome
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_gpu
    volumes:
      # - .:/home
      - .:/aincome
    # working_dir: /home
    working_dir: /aincome
    tty:  true
    ports:
      - "7171:7171"
      - "5151:5151"
    # command: jupyter notebook --config=/home/john/mystuff/jupyter_notebook_config.json --port=7171 --ip=0.0.0.0 --allow-root --NotebookApp.token=''

