version: '3.8'
services:
  aincome-app:
    container_name: aincome
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_gpu
    volumes:
      # - .:/home
      - .:/aincome
    # working_dir: /home
    working_dir: /aincome
    tty:  true
    ports:
      - "7171:7171"
      - "5151:5151"
    command: jupyter-lab --port=7171 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    
  tb-app:
    container_name: tb
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_tb
    volumes:
      # - .:/home
      - .:/home
    ports:
      - "10000:6006"

